# Abyssal Cobalt Base
$color = rgba(0A192FFF)

# Transparent Glass Center (using Surface0)
$inner_color = rgba(162D4ACC)

# Vista Blue Outer Border
$outer_color = rgba(0096FFFF)

# Ice White Font for that "Glow"
$font_color = rgba(E0FBFFFF)

# Citrus Yellow for Checking state
$check_color = rgba(FFE27AFF)

# Candy Red for Failure state
$fail_color = rgba(FF5D8FFF)

# Sapphire Cyan Aura for the "Glow" effect
$outer_aura = rgba(00D4FF8C)