# Base
$color = rgba(29, 32, 33, 1.0)                 # bg0
$inner_color = rgba(50, 48, 47, 0.8)           # bg_statusline2

# Primary (green)
$outer_color = rgba(169, 182, 101, 1.0)        # #A9B665
$outer_aura  = rgba(169, 182, 101, 0.55)

# Text
$font_color = rgba(212, 190, 152, 1.0)         # fg0

# States
$check_color = rgba(216, 166, 87, 1.0)         # yellow (#D8A657)
$fail_color  = rgba(234, 105, 98, 1.0)         # red (#EA6962)

# input-field {
#     monitor =
#     size = 650, 100
#     position = 0, 0
#     halign = center
#     valign = center

#     inner_color = $inner_color
#     outer_color = $outer_color
#     outer_color_inactive = $outer_aura
#     outline_thickness = 4
    
#     font_family = CaskaydiaMono Nerd Font
#     font_color = $font_color

#     placeholder_text = Enter Password 🔑
#     check_color = $check_color
#     fail_color = $fail_color
#     fail_text = <i>$FAIL ($ATTEMPTS)</i>

#     rounding = 4
#     shadow_passes = 0
#     fade_on_empty = false
# }