# Font
font_family CaskaydiaMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 10
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0
background_tint 0.25
background_opacity 0.8

# Keybindings
map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
include colors.conf
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

shell /usr/bin/zsh

foreground              #d4be98
background              #282828
selection_foreground    #282828
selection_background    #d4be98

cursor                  #d4be98
cursor_text_color       #282828

url_color               #a9b665

active_border_color     #a89984
inactive_border_color   #3c3836
bell_border_color       #d8a657

active_tab_foreground   #282828
active_tab_background   #a9b665
inactive_tab_foreground #d4be98
inactive_tab_background #3c3836
tab_bar_background      #1d2021

mark1_foreground #282828
mark1_background #a9b665
mark2_foreground #282828
mark2_background #d8a657
mark3_foreground #282828
mark3_background #e78a4e

# black / gray
color0 #3c3836
color8 #a89984

# red
color1 #ea6962
color9 #ea6962

# green (primary)
color2  #a9b665
color10 #a9b665

# yellow (secondary)
color3  #d8a657
color11 #d8a657

# orange replaces "blue" slot (intentional warmth)
color4  #e78a4e
color12 #e78a4e

# magenta (keep minimal use)
color5  #d3869b
color13 #d3869b

# aqua (downgraded role)
color6  #89b482
color14 #89b482

# white
color7  #d4be98
color15 #a89984