# Hyprlock Colors - Variant 1 (Teal 185°)

# Main Background (Crust 185°)
$color = rgba(17, 31, 34, 1.0)

# Input Field Background (Base 185°)
$inner_color = rgba(30, 50, 54, 0.8)

# Active/Primary Accents (Teal)
$outer_color = rgba(139, 213, 202, 1.0)
$font_color = rgba(139, 213, 202, 1.0)
$outer_aura = rgba(139, 213, 202, 0.55)

# Status Accents (Yellow & Red)
$check_color = rgba(238, 212, 159, 1.0)
$fail_color = rgba(237, 135, 150, 1.0)

#input-field {
    #monitor =
    #size = 650, 100
    #position = 0, 0
    #halign = center
    #valign = center

    #inner_color = $inner_color
    #outer_color = $outer_color
    #outer_color_inactive = $outer_aura
    #outline_thickness = 4
    
    #font_family = CaskaydiaMono Nerd Font
    #font_color = $font_color

    #placeholder_text = Enter Password 🔑
    #check_color = $check_color
    #fail_color = $fail_color
    #fail_text = <i>$FAIL ($ATTEMPTS)</i>

    #rounding = 4
    #shadow_passes = 0
    #fade_on_empty = false
#}