# Font
font_family CaskaydiaMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 10
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0
background_tint 0.25
background_opacity 0.8

# Keybindings
map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
include colors.conf
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

shell /usr/bin/zsh

# vim:ft=kitty

## name:     Catppuccin Kitty Macchiato Teal (Variant 1 - 185°)
## author:   Catppuccin Org (Modified for Teal Neutrals)
## license:  MIT
## blurb:    Soothing modern teal pastel theme!

# The basic colors
foreground              #c0dce0
background              #1e3236
selection_foreground    #1e3236
selection_background    #8bd5ca

# Cursor colors
cursor                  #8bd5ca
cursor_text_color       #1e3236

# URL underline color when hovering with mouse
url_color               #91d7e3

# Kitty window border colors
active_border_color     #8bd5ca
inactive_border_color   #415c61
bell_border_color       #eed49f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #111f22
active_tab_background   #8bd5ca
inactive_tab_foreground #c0dce0
inactive_tab_background #182a2d
tab_bar_background      #111f22

# Colors for marks (marked text in the terminal)
mark1_foreground #1e3236
mark1_background #8bd5ca
mark2_foreground #1e3236
mark2_background #91d7e3
mark3_foreground #1e3236
mark3_background #7dc4e4

# The 16 terminal colors

# black (Surface1 and Surface2 - 185°)
color0 #415c61
color8 #537075

# red
color1 #ed8796
color9 #ed8796

# green (Standard Macchiato Green)
color2  #a6da95
color10 #a6da95

# yellow
color3  #eed49f
color11 #eed49f

# blue
color4  #8aadf4
color12 #8aadf4

# magenta
color5  #f5bde6
color13 #f5bde6

# cyan (Sky 185°)
color6  #91d7e3
color14 #91d7e3

# white (Subtext1 and Subtext0 - 185°)
color7  #adcfd4
color15 #99bec4