[opener]
# Edit files (default editor, VSCode on Windows)
edit = [
	{ run = '${EDITOR:-nvim} %s', desc = "Default Editor", block = true, for = "unix" },
	{ run = 'code %s',    orphan = true, desc = "VS Code",         for = "windows" },
	{ run = 'code -w %s', block = true,  desc = "VS Code (block)", for = "windows" },
]

# Open with default system handler
open = [
	{ run = 'xdg-open %s1',                desc = "Open (System Default)", for = "linux" },
	{ run = 'open %s',                     desc = "Open (System Default)", for = "macos" },
	{ run = 'start "" %s1', orphan = true, desc = "Open (System Default)", for = "windows" },
	{ run = 'termux-open %s1',             desc = "Open (System Default)", for = "android" },
]

# Reveal in file manager
reveal = [
	{ run = 'xdg-open %d1',                desc = "Reveal", for = "linux" },
	{ run = 'open -R %s1',                 desc = "Reveal", for = "macos" },
	{ run = 'explorer /select,%s1', orphan = true, desc = "Reveal", for = "windows" },
	{ run = 'termux-open %d1',             desc = "Reveal", for = "android" },
]

# Extract archives
extract = [
	{ run = 'ya pub extract --list %s', desc = "Extract here", for = "unix" },
	{ run = 'ya pub extract --list %s', desc = "Extract here", for = "windows" },
]

# Play media
play = [
	{ run = 'mpv --force-window %s', orphan = true, desc = "Play (mpv)", for = "unix" },
	{ run = 'mpv --force-window %s', orphan = true, desc = "Play (mpv)", for = "windows" },
]

# PDFs
pdf = [
	{ run = 'zathura %s', orphan = true, desc = "Zathura", for = "linux" },
]

[open]
# Open files and directories in the editor (lazyvim).
rules = [
	{ url = "*/", use = "edit" },
	{ url = "*", use = "edit" },
]

[pick]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [ 0, 1, 50, 7 ]
