# Hyprland Colors - Gruvbox Material (Medium Dark)
$activeBorderColor = rgb(89b482)
$inactiveBorderColor = rgb(504847)
$textColor = rgb(d4be98)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor

    groupbar {
        col.active = $activeBorderColor
        col.inactive = $inactiveBorderColor
        text_color = $textColor
    }
}