[colors.primary]
background = "#1e2030"
foreground = "#cad3f5"
dim_foreground = "#8087a2"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "#1e2030"
cursor = "#8bd5ca"

[colors.vi_mode_cursor]
text = "#1e2030"
cursor = "#91d7e3"

[colors.search.matches]
foreground = "#1e2030"
background = "#91d7e3"

[colors.search.focused_match]
foreground = "#1e2030"
background = "#a6da95"

[colors.footer_bar]
foreground = "#1e2030"
background = "#5b6078"

[colors.hints.start]
foreground = "#1e2030"
background = "#91d7e3"

[colors.hints.end]
foreground = "#1e2030"
background = "#5b6078"

[colors.selection]
text = "#1e2030"
background = "#8bd5ca"

[colors.normal]
black   = "#494d64"
red     = "#ed8796"
green   = "#a6da95"
yellow  = "#eed49f"
blue    = "#8aadf4"
magenta = "#c6a0f6"
cyan    = "#8bd5ca"
white   = "#b8c0e0"

[colors.bright]
black   = "#5b6078"
red     = "#ed8796"
green   = "#a6da95"
yellow  = "#eed49f"
blue    = "#8aadf4"
magenta = "#c6a0f6"
cyan    = "#8bd5ca"
white   = "#cad3f5"

[[colors.indexed_colors]]
index = 16
color = "#8bd5ca"

[[colors.indexed_colors]]
index = 17
color = "#91d7e3"
