include=~/.local/share/omarchy/default/mako/core.ini

# Frutiger Aqua (Deep Sea)
# Abyssal Cobalt background with 95% opacity for a glass look
background-color=#0a192ff2

# Vista Blue border
border-color=#0096ff

# Ice White text for high-contrast "glow"
text-color=#e0fbff

# Border radius for that "Rounded Aero" feel
border-size=2
border-radius=8

# Progress bar (Sapphire Cyan)
progress-color=over #00d4ff
