source = ~/.config/omarchy/current/theme/hyprlock.conf

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
   monitor =
   size = 650, 100
   outline_thickness = 3
    
    # Outer border: Aero Grass Green to Accent Green liquid gradient
    outer_color = rgba(57FA6FFF) rgba(139228B3) 45deg
    # Inner glass: Dark Grey with high transparency
    inner_color = rgba(27, 27, 27, 0.85)
    # Text: Glowing White
    font_color = rgb(236, 255, 224)
    
    fade_on_empty = false
    placeholder_text = <span weight="bold" foreground="##C0FEBD"><i>Enter Password 🔑</i></span>
    
    # State Colors
    check_color = rgb(255, 215, 0)      # Warning Sun Yellow
    fail_color = rgb(255, 51, 51)       # Glossy Stoplight Red
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    
    rounding = 12
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    
    position = 0, 0
    halign = center
    valign = center

    #The "Aero Glow" effect
    shadow_passes = 2
    shadow_size = 10
    shadow_color = rgba(87, 250, 111, 0.4)
}

# input-field {
#     monitor =
#     size = 650, 100
#     position = 0, 0
#     halign = center
#     valign = center

#     inner_color = $inner_color
#     outer_color = $outer_color
#     outer_color_inactive = $outer_aura
#     outline_thickness = 4
    
#     font_family = CaskaydiaMono Nerd Font
#     font_color = $font_color

#     placeholder_text = Enter Password 🔑
#     check_color = $check_color
#     fail_color = $fail_color
#     fail_text = <i>$FAIL ($ATTEMPTS)</i>

#     rounding = 4
#     shadow_passes = 0
#     fade_on_empty = false
# }

auth {
    fingerprint:enabled = false
}
