source = ~/.config/omarchy/current/theme/hyprlock.conf

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 320, 70
    outline_thickness = 4
    
    # BORDER: A 3-color gradient to get that "liquid/plastic" Aero edge
    # Transitions from Lemon to Aero Green to Emerald
    outer_color = $lemon $aero_green $emerald 30deg
    
    # INNER: Deep dark glass
    inner_color = $surface_dark
    
    # TEXT: Glow White with a bold placeholder
    font_color = $glow_white
    fade_on_empty = false
    placeholder_text = <span weight="bold" foreground="##EAFF00"><i>Enter Password 🔑</i></span>
    
    # STATE COLORS: Glossy Red and Warning Yellow
    check_color = $sun_yellow
    fail_color = rgb(FF3333) 
    
    rounding = 20 # High rounding for that "pill" Aero shape
    dots_size = 0.3
    dots_spacing = 0.3
    dots_center = true
    
    position = 0, -50
    halign = center
    valign = center

    # HIGH GLOW: Using the Lemon/Green mix for a "neon glass" shadow
    shadow_passes = 3
    shadow_size = 12
    shadow_color = rgba(234, 255, 0, 0.3) 
}

# input-field {
#     monitor =
#     size = 650, 100
#     position = 0, 0
#     halign = center
#     valign = center

#     inner_color = $inner_color
#     outer_color = $outer_color
#     outer_color_inactive = $outer_aura
#     outline_thickness = 4
    
#     font_family = CaskaydiaMono Nerd Font
#     font_color = $font_color

#     placeholder_text = Enter Password 🔑
#     check_color = $check_color
#     fail_color = $fail_color
#     fail_text = <i>$FAIL ($ATTEMPTS)</i>

#     rounding = 4
#     shadow_passes = 0
#     fade_on_empty = false
# }

auth {
    fingerprint:enabled = false
}
