# Hyprland Colors - Gruvbox Mix (Dark Hard)
$activeBorderColor = rgb(b0b846)
$inactiveBorderColor = rgb(504945)
$textColor = rgb(e2cca9)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor

    groupbar {
        col.active = $activeBorderColor
        col.inactive = $inactiveBorderColor
        text_color = $textColor
    }
}