# Font
font_family CaskaydiaMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 10
window_padding_height 14
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0
background_tint 0.25
background_opacity 0.8

# Keybindings
map F11 toggle_fullscreen
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
include colors.conf
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

shell /usr/bin/zsh

foreground              #e2cca9
background              #282828
selection_foreground    #282828
selection_background    #e2cca9

cursor                  #e2cca9
cursor_text_color       #282828

url_color               #b0b846

active_border_color     #a89984
inactive_border_color   #3c3836
bell_border_color       #e9b143

active_tab_foreground   #282828
active_tab_background   #b0b846
inactive_tab_foreground #e2cca9
inactive_tab_background #3c3836
tab_bar_background      #1d2021

mark1_foreground #282828
mark1_background #b0b846
mark2_foreground #282828
mark2_background #e9b143
mark3_foreground #282828
mark3_background #f28534

# black / gray
color0 #3c3836
color8 #a89984

# red
color1 #f2594b
color9 #f2594b

# green (primary)
color2  #b0b846
color10 #b0b846

# yellow (secondary)
color3  #e9b143
color11 #e9b143

# orange (tertiary replaces blue slot)
color4  #f28534
color12 #f28534

# magenta (optional)
color5  #d3869b
color13 #d3869b

# aqua (support only)
color6  #8bba7f
color14 #8bba7f

# white
color7  #e2cca9
color15 #a89984