background = 0a2f0d
foreground = ecffe0
cursor-color = 5cff47
cursor-text = 0a2f0d
selection-background = 5cff47
selection-foreground = 0a2f0d

palette = 0=#164a19
palette = 1=#ff5d8f
palette = 2=#5cff47
palette = 3=#ffe27a
palette = 4=#5cff47
palette = 5=#c0a3ff
palette = 6=#5cff47
palette = 7=#c0febd
palette = 8=#327b36
palette = 9=#ff5d8f
palette = 10=#5cff47
palette = 11=#ffe27a
palette = 12=#5cff47
palette = 13=#c0a3ff
palette = 14=#89dceb
palette = 15=#ecffe0
