include=~/.local/share/omarchy/default/mako/core.ini

# Frutiger Eco
# Abyssal Cobalt background with 95% opacity for a glass look
background-color=#0a192ff2

# Aero Grass Green border
border-color=#5cff47

# Ice White text for high-contrast "glow"
text-color=#e0fbff

# Border radius for that "Rounded Aero" feel
border-size=2
border-radius=8

# Progress bar (True Vista Blue)
progress-color=over #5cff47
