background = 1b1b1b
foreground = ecffe0
cursor-color = 57fa6f
cursor-text = 1b1b1b
selection-background = 57fa6f
selection-foreground = 1b1b1b

palette = 0=#2b2b2b
palette = 1=#ff3333
palette = 2=#5CFF47
palette = 3=#ffd700
palette = 4=#0096ff
palette = 5=#c0a3ff
palette = 6=#00f5d4
palette = 7=#c0febd
palette = 8=#4e4e4e
palette = 9=#ff3333
palette = 10=#5CFF47
palette = 11=#ffd700
palette = 12=#0096ff
palette = 13=#c0a3ff
palette = 14=#89dceb
palette = 15=#ecffe0
