background = 131813
foreground = ecffe0
cursor-color = 5cff47
cursor-text = 131813
selection-background = 5cff47
selection-foreground = 131813

palette = 0=#151a15
palette = 1=#ff3333
palette = 2=#5cff47
palette = 3=#ffd700
palette = 4=#eaff00
palette = 5=#ffd700
palette = 6=#d4ff00
palette = 7=#c0febd
palette = 8=#455545
palette = 9=#ff3333
palette = 10=#5cff47
palette = 11=#ffd700
palette = 12=#eaff00
palette = 13=#ffd700
palette = 14=#a0ff20
palette = 15=#ecffe0
