include=~/.local/share/omarchy/default/mako/core.ini

# Frutiger Dark Aero
# Studio Black background with 95% opacity for a glass look
background-color=#1b1b1bf2

# Aero Grass Green border
border-color=#5CFF47

# Glow White text for high-contrast "glow"
text-color=#ecffe0

# Border radius for that "Rounded Aero" feel
border-size=2
border-radius=8

# Progress bar (True Vista Blue)
progress-color=over #0096ff
