[colors.primary]
background = "#F1DFC0"     
foreground = "#2C3043"     
dim_foreground = "#6C6F85" 
bright_foreground = "#2C3043"

[colors.cursor]
text = "#F1DFC0"           
cursor = "#7287FD"         

[colors.vi_mode_cursor]
text = "#F1DFC0"           
cursor = "#1E66F5"         

[colors.search.matches]
foreground = "#F1DFC0"
background = "#1E66F5"     

[colors.search.focused_match]
foreground = "#F1DFC0"
background = "#179299"     

[colors.footer_bar]
foreground = "#F1DFC0"
background = "#6C6F85"     

[colors.hints.start]
foreground = "#F1DFC0"
background = "#1E66F5"

[colors.hints.end]
foreground = "#F1DFC0"
background = "#6C6F85"

[colors.selection]
text = "#F1DFC0"
background = "#209FB5"     

[colors.normal]
black   = "#DCE0E8"        
red     = "#E64553"        
green   = "#40A02B"        
yellow  = "#F8B115"        
blue    = "#1E66F5"        
magenta = "#9171D8"        
cyan    = "#209FB5"      
white   = "#4C4F69"        

[colors.bright]
black   = "#ACB0BE"        
red     = "#E64553"
green   = "#40A02B"
yellow  = "#F8B115"
blue    = "#7287FD"      
magenta = "#E574BC"        
cyan    = "#04A5E5"      
white   = "#2C3043"        

[[colors.indexed_colors]]
index = 16
color = "#FE812D"       

[[colors.indexed_colors]]
index = 17
color = "#E8A598"        