# Ghostty Palette - Tropical City Pop

background = #F1DFC0
foreground = #2C3043

# Normal colors
palette = 0=#DCE0E8
palette = 1=#E64553
palette = 2=#40A02B
palette = 3=#F8B115
palette = 4=#1E66F5
palette = 5=#9171D8
palette = 6=#209FB5
palette = 7=#4C4F69

# Bright colors
palette = 8=#ACB0BE
palette = 9=#EE867E
palette = 10=#40A02B
palette = 11=#F8B115
palette = 12=#7287FD
palette = 13=#E574BC
palette = 14=#04A5E5
palette = 15=#2C3043

# Cursor
cursor-color = #FE812D
cursor-text = #F1DFC0

# Selection
selection-background = #209FB5
selection-foreground = #F1DFC0
