$activeBorderColor = rgb(F8B115)
$inactiveBorderColor = rgb(F1DFC0)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
}
