# vim:ft=kitty

## name:     Tropical City Pop
## author:   Raphael
## license:  MIT
## upstream:
## blurb:    High-saturation, retro-tech theme

# The basic colors
foreground              #2C3043
background              #F1DFC0
selection_foreground    #F1DFC0
selection_background    #F8B115

# Cursor colors
cursor                  #F8B115
cursor_text_color       #F1DFC0

# URL underline color when hovering with mouse
url_color               #1E66F5

# Kitty window border colors
active_border_color     #F8B115
inactive_border_color   #ACB0BE
bell_border_color       #FE812D

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #F1DFC0
active_tab_background   #2C3043
inactive_tab_foreground #4C4F69
inactive_tab_background #DCE0E8
tab_bar_background      #DCC9A9

# Colors for marks (marked text in the terminal)
mark1_foreground #F1DFC0
mark1_background #9171D8
mark2_foreground #F1DFC0
mark2_background #E574BC
mark3_foreground #F1DFC0
mark3_background #04A5E5

# The 16 terminal colors

# black (Dark tones from the "ink" and shadows)
color0 #2C3043
color8 #4C4F69

# red (Vibrant City Pop Red)
color1 #E64553
color9 #E64553

# green (Neo-retro synth green)
color2  #40A02B
color10 #40A02B

# yellow (Anchor Yellow)
color3  #F8B115
color11 #F8B115

# blue (Electric blue from the skies/tech)
color4  #1E66F5
color12 #1E66F5

# magenta (Bubblegum/Pink neon)
color5  #E574BC
color13 #E574BC

# cyan (Retro digital teal)
color6  #179299
color14 #179299

# white (Paper/Beige tones)
color7  #ACB0BE
color15 #F1DFC0
