## name:     Frutiger Eco
## author:   Raphael Andrews
## blurb:    Abyssal emerald base with high-vibrancy aero accents.

# The basic colors
foreground              #ECFFE0
background              #0A2F0D
selection_foreground    #0A2F0D
selection_background    #5CFF47

# Cursor colors
cursor                  #5CFF47
cursor_text_color       #0A2F0D

# URL underline color
url_color               #89DCEB

# Kitty window border colors
active_border_color     #5CFF47
inactive_border_color   #164A19
bell_border_color       #FFE27A

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #051A07
active_tab_background   #5CFF47
inactive_tab_foreground #C0FEBD
inactive_tab_background #164A19
tab_bar_background      #072209

# Colors for marks
mark1_foreground #0A2F0D
mark1_background #B8C0FF
mark2_foreground #0A2F0D
mark2_background #C0A3FF
mark3_foreground #0A2F0D
mark3_background #00F5D4

# The 16 terminal colors

# black (Surface/Overlay tones)
color0 #164A19
color8 #327B36

# red (Candy Red)
color1 #FF5D8F
color9 #FF5D8F

# green (Aero Grass Green)
color2  #5CFF47
color10 #5CFF47

# yellow (Citrus Yellow)
color3  #FFE27A
color11 #FFE27A

# blue (Aero Grass Green)
color4  #5CFF47
color12 #5CFF47

# magenta (Mauve/Lavender mix)
color5  #C0A3FF
color13 #C0A3FF

# cyan (True Vista Blue)
color6  #0096FF
color14 #89DCEB

# white (Ice/Subtext tones)
color7  #C0FEBD
color15 #ECFFE0