## name:     Frutiger Dark Aero
## author:   Raphael Andrews
## blurb:    Abyssal emerald base with high-vibrancy aero accents.

# The basic colors
foreground              #ECFFE0
background              #1b1b1b
selection_foreground    #1b1b1b
selection_background    #5CFF47

# Cursor colors
cursor                  #5CFF47
cursor_text_color       #1b1b1b

# URL underline color
url_color               #89DCEB

# Kitty window border colors
active_border_color     #5CFF47
inactive_border_color   #2b2b2b
bell_border_color       #FFE27A

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #080808
active_tab_background   #5CFF47
inactive_tab_foreground #C0FEBD
inactive_tab_background #2b2b2b
tab_bar_background      #1b1b1b

# Colors for marks
mark1_foreground #1b1b1b
mark1_background #B8C0FF
mark2_foreground #1b1b1b
mark2_background #C0A3FF
mark3_foreground #1b1b1b
mark3_background #00F5D4

# The 16 terminal colors

# black (Surface/Overlay tones)
color0 #2b2b2b
color8 #4e4e4e

# red (Candy Red)
color1 #FF5D8F
color9 #FF5D8F

# green (Aero Grass Green)
color2  #5CFF47
color10 #5CFF47

# yellow (Citrus Yellow)
color3  #FFE27A
color11 #FFE27A

# blue (True Vista Blue)
color4  #0096FF
color12 #0096FF

# magenta (Mauve/Lavender mix)
color5  #C0A3FF
color13 #C0A3FF

# cyan (Bio-Mint)
color6  #00F5D4
color14 #89DCEB

# white (Ice/Subtext tones)
color7  #C0FEBD
color15 #ECFFE0